# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: db22d5b6dec18aff20fd06a3c85602e76d69cd2f6dfb523c8c7072b1eba88398f92d5b76ef759d8b08d21d30f202dfea056be8816d2ce44af10eb3a214e8bf4b

test:
  secret_key_base: acf5a85c7dd2a242c78f80ac91e203aca75e9bc62faf78ae362c29bf64a66d1eb7aa08b3cdc1a93841eee1bbbbddeda4137f400c3e5e0e6ae394db6c85b8801f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
